### ISSUE TITLE
Redirect issue from index.php

### ISSUE THREAD

**Issue by lindsay-whittle-sift** [kevin-chilcott-sift/vagrant-project#4]
Once Kevin's form is submitted, it redirects to a 'Not found' page. I suggest to change this to make it redirect to the correct page. Once I have amended this, I will push back into Git.

**Comment by kevin-chilcott-sift** [comment]
I will get on this as soon as possible, thanks again for taking a look for me.

**Comment by kevin-chilcott-sift** [comment]
Hi Lindsay I have successfully completed this amend, if you would still like to take a look its in the "3rd times the charm with these links" commit.
